
version: 2

sources:
  - name: thelook_ecommerce
    database: manifest-access-428617-g7
    schema: raw_datasource
    tables:
      - name: distribution_centers
      - name: orders
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: created_at
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
          - name: status
            tests:
              - accepted_values:
                  values: ['Cancelled']
      - name: orders_items

